name: Update Trimmed Playlist and EPG
on:
  schedule:
    - cron: '0 0,12 * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests lxml

      - name: Run All-in-One Script
        run: python update_all.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add trimmed.m3u trimmed_epg.xml.gz
          git commit -m "Automated update: M3U and EPG" || exit 0
          git push
